### ISSUE TITLE
Find solution to use gpg through application

### ISSUE THREAD

**Issue by RGamz** [agoalofalife/password-frog#1]
At the moment we don't have any information - how use gpg utility through application. I am used to use it in console and obviously we must do it in node js. Fast research lead me to this package https://www.npmjs.com/package/gpg
I suppose there are a few options how to resolve it.
The first one is install gpg in background in appeal to it through shell call. By the way, the process of installation might be more complicated because of OS(operation system).
The second one, find preset gpg in node js package or some way to use this utility without installation.
The main task to ensure that we can use gpg in our application and have work way.

**Comment by RGamz** [comment]
@agoalofalife  

GPG is licensed under GPLv3, which is a copyleft license requiring that derivative works are also distributed under GPLv3.

**Obligations:**
Source Code Availability: _You must make your application's source code available under GPLv3._
License Notices: _Include the GPLv3 license text with your application and inform users of their rights._

**Conclusion on Licensing:**

If you are comfortable releasing your app under GPLv3, then bundling GPG binaries is acceptable.
If you prefer to keep your app proprietary or under a different license, bundling GPG binaries may not be feasible due to the licensing restrictions.

**Comment by RGamz** [comment]
@agoalofalife  the  [](https://www.npmjs.com/package/gpg) module requires the GPG binary to be installed on the user's system and accessible via the $PATH environment variable. This contradicts the requirement of not forcing users to install GPG by themselves or separately. 

Also Installation methods for GPG differ across operating systems, potentially complicating the user experience.

To avoid requiring users to install GPG themselves, we can bundle the GPG binaries with the Electron app and configure node-gpg to use these binaries. This will mean that we will need to manage and update GPG binaries for multiple platforms.

**Comment by RGamz** [comment]
@agoalofalife there is an alternative solution : https://openpgpjs.org/ 

**Ease of Integration:** Pure JavaScript library that integrates smoothly with Electron.
**Licensing Flexibility:** LGPL-3.0 license allows inclusion in proprietary software under certain conditions.
**Simplified Deployment:** No external binaries or dependencies to manage.
**Consistent User Experience:** Uniform functionality across all supported platforms.

So please decide and give your opinion on which way to go. 
Thanks

**Comment by agoalofalife** [comment]
Let's consider other alternatives as js library for encrypt and decrypt information

**Comment by RGamz** [comment]
> Let's consider other alternatives as js library for encrypt and decrypt information

hi @agoalofalife , what do you think about this Standford library? https://bitwiseshiftleft.github.io/sjcl/

**Comment by agoalofalife** [comment]
I looked at this package and I think it worth to take it.
